### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by AleyRobotics** [fdivitto/sbus#1]
/Arduino/libraries/sbus/sbus.cpp:259:16: error: invalid conversion from 'volatile uint8_t* {aka volatile unsigned char*}' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
   s_pin        = pinOfPin(pin);
                ^
exit status 1

Arduino IDE 1.8.5

**Comment by AleyRobotics** [comment]
fixed. Please merge pull request

**Comment by fdivitto** [comment]
thanks!
